<div style="text-align: center;">
    <img src="../images/banner.png" alt="Banner curso" style="width:80%">
</div>

<div style="display: flex; justify-content: center;">
    <h1>Elementos de Programación</h1>
</div>

## Temario

1. Conceptos Fundamentales de los lenguajes de programación  

    + Breve introducción a los lenguajes de programación.
    + Tipos de datos: enteros, decimales, lógicas y cadenas.
    + Declaración, asignación e inicialización.
    + Convenciones y palabras reservadas.
    +Tipado: estático vs dinámico

2. Operadores

    + Operadores aritméticos y orden de precedencia.
    + Operadores de Asignación.
    + Operadores de incremento y decremento.
    + Operadores de relación e igualdad.
    + Operadores lógicos.

3. Estructuras de control

    + Estructura secuencial.
    + Estructura selectiva.
    + Estructura iterativa.

4. Funciones

    + Creación y llamada de funciones
    + Parámetros y argumentos.
    + Paso de argumentos por valor y referencia.
    + Recuperación de valores.
    
5. Estructura de datos

    + Tipos de estructura de datos.
    + Arreglos en python e introducción a Numpy: declaración y manipulación.

## 1. Conceptos Fundamentales de los lenguajes de programación

### Breve introducción a los lenguajes de programación.

Un lenguaje de programación es un sistema formal de comunicación diseñado para expresar instrucciones que pueden ser entendidas y ejecutadas por una computadora. Estos lenguajes permiten a los programadores escribir programas, que son conjuntos de instrucciones que dictan cómo una máquina debe comportarse o realizar tareas específicas.


__Características Clave de un Lenguaje de Programación:__

- Sintaxis:

La sintaxis de un lenguaje de programación se refiere a las reglas y estructuras que se utilizan para escribir el código, siendo equivalente a las reglas gramaticales y de redacción que rigen a cada idioma. 

Por ejemplo, la sintaxis para definir una función en Python es diferente a la de Java:
```python
    # Sintaxis Python
    def suma(a, b):
        return a + b
```
```java
    // Sintaxis Java
    public int suma(int a, int b) {
        return a + b;
    }
```
- Semántica:

La semántica en programación se refiere al significado de nuestras instrucciones en un lenguaje de programación. Es lo que determina cómo se deben interpretar y ejecutar nuestras acciones en el mundo digital.


In [1]:
numero_1 = 5 
numero_2 = 3 
resultado = numero_1 + numero_2 
print(resultado)

8


In [2]:
cadena_1 = "Chicos de ambientales"
numero_1 = 12
resultado = cadena_1 + numero_1
print(resultado)

TypeError: can only concatenate str (not "int") to str

In [6]:
cadena_1 = "Chicos de ambientales"
cadena_2 = "van a ser hackers de python"
resultado = cadena_1 + cadena_2
print(resultado)

Chicos de ambientalesvan a ser hackers de python


In [4]:
resultado = cadena_1 + " " + cadena_2
print(resultado)

Chicos de ambientales van a ser hackers de python


- Abstracción:

Los lenguajes de programación proporcionan varios niveles de abstracción para facilitar la programación. Lenguajes de bajo nivel como el ensamblador están más cerca del lenguaje máquina, mientras que lenguajes de alto nivel como Python o Java abstraen detalles complejos del hardware.

__Paradigmas de Programación o estilos de programación:__

- Programación imperativa: Especifica una secuencia de operaciones para realizar una tarea.

- Programación declarativa: Describe qué se debe hacer, no cómo hacerlo.

- Programación orientada a objetos: Organiza el código en objetos que tienen propiedades y comportamientos.

- Programación funcional: Trata la computación como la evaluación de funciones matemáticas.


__Tipos de Lenguajes de Programación__

- Lenguajes de bajo nivel:

    Un lenguaje de programación de bajo nivel proporciona poca o ninguna abstracción de la arquitectura del sistema del ordenador, es decir, se escribe código que es estructuralmente parecido a las instrucciones del procesador. Mayormente, con este término se refiere al código máquina y/o al lenguaje ensamblador.

- Lenguajes de alto nivel:

    Un lenguaje de programación de alto nivel proporciona una gran abstracción entre el lenguaje de la máquina y el lenguaje humano, siendo mucho más fácil de leer, escribir y/o automatizar, ya que oculta detalles del sistema del ordenador para ejecutarlos tras el telón, como por ejemplo, la gestión de la memoria.


__El proceso de programación__

> La programación es un proceso de resolución de problemas. Para resolver estos problemas se requieren técnicas diferentes que comprenden desde el análisis del problema, especificación de requisitos o requerimientos y las etapas de diseño denominadas algoritmos.

La elección del lenguaje de programación puede depender de muchos factores, incluyendo el dominio de aplicación, las preferencias personales, el rendimiento requerido y la comunidad de soporte disponible.

__Interpretación de los lenguajes de Programación__

El mundo como lo conocemos depende de los lenguajes de programación debido a que el software que utilizamos en nuestra vida diaria ha sido escrito en alguno de ellos. Pero los programas escritos para que puedan ser ejecutados antes necesitan ser traducidos al lenguaje de la computadora para que esta entienda que tiene que hacer.

El proceso de traducción se le conoce como __compilación__ y al software usado para traducir se le llama _compilador_ o _interprete_, según sea el caso.

Un __compilador__ traduce el código de un lenguaje de programación de alto nivel a código máquina antes de que el programa se ejecute. Una función importante del compilador es informar de cualquier error en el programa fuente que detecte durante el proceso de traducción.

Un __intérprete__ traduce el código escrito en un lenguaje de programación de alto nivel a código máquina línea por línea a medida que se ejecuta el código. En caso de detectar un error mientras se ejecuta, interrumpe el programa y muestra información acerca del este.

#### Lenguaje de Programación Python

_Python_ es un lenguaje de programación de alto nivel que ha ganado una gran popularidad debido a su versatilidad, facilidad de uso y amplia gama de bibliotecas. Entre las principales ventajas de usar Python se encuentran:

1. Sintaxis clara y legible.

2. Gran comunidad y soporte.

3. Versatilidad y portabilidad.

4. Amplia gama de bibliotecas y frameworks.

5. Código rápido y eficiente.

6. Código robusto y escalable.

7. Facilidad de aprendizaje.

8. Amplia gama de aplicaciones:

    - Análisis de datos y ciencia de datos
    - Aprendizaje automático e inteligencia artificial
    - Desarrollo web y aplicaciones web
    - Desarrollo de escritorio
    - Automatización de tareas
    - Scripting y administración de sistemas
    - Desarrollo de juegos
    - Visualización de datos

### Tipos de datos.

Los tipos de datos son la base fundamental para organizar y manipular la información en los lenguajes de programación. Cierto tipo de dato define el tipo de valor que se puede manejar y las operaciones que se pueden realizar con ese tipo de dato.

#### Unidad de Información
Una unidad de información es una medida básica utilizada para medir la cantidad de datos o información. 
Estas unidades son fundamentales en la informática y las telecomunicaciones, donde se utilizan para:

- describir el tamaño de archivos 
- la capacidad de almacenamiento
- la velocidad de transmisión de datos. 

Las unidades de información se basan en el concepto de bits, bytes y palabra, que son las unidades más fundamentales en la representación digital de la información.

Principales unidades de información:
- Bit: Es la unidad más básica de información. Un bit puede representar dos estados posibles, típicamente 0 o 1. Se utiliza para representar la unidad mínima de información en un sistema binario.
- Byte: Un byte es un grupo de 8 bits. Es la unidad básica utilizada para medir el tamaño de archivos y la capacidad de almacenamiento.
- Palabra: Son grupos de bits que tienen un tamaño fijo. Es una unidad básica de datos que un procesador de computadora puede manejar y procesar como un único conjunto en una operación. La longitud de una palabra depende de la arquitectura del sistema, y suele estar relacionada con la cantidad de bits que la CPU puede procesar simultáneamente en una operación.

Por ejemplo:
- En una arquitectura de 32 bits, la longitud de una palabra es de 32 bits (4 bytes).
- En una arquitectura de 64 bits, la longitud de una palabra es de 64 bits (8 bytes).


En general, los tipos de datos se pueden clasificar en dos categorías principales:

1. Tipos de datos primitivos:

Los tipos de datos primitivos son los tipos de datos más básicos que ofrece un lenguaje de programación. Son indivisibles y solo pueden almacenar un único valor. Los tipos de datos primitivos más comunes incluyen:
| Categoría | Tipo de Dato | Descripción | Ejemplos | Tamaño en bytes |
| :---: | :---: | :--- | :---: | :---: |
| Tipo Numérico | Entero | Números enteros positivos, negativos o cero. Comprende un rango de valores aproximadamente de -9,223,372,036,854,775,808 a 9,223,372,036,854,775,807. | ```1, -10, 0, 200``` | 4 u 8 |
| Tipo Numérico | Float | Números de punto flotante. Comprende un rango de valores aproximadamente de ±1.79769313486231570E+308 (precisión de 15-16 dígitos decimales). | ```3.1416, -5.2, 10.0, 0.33``` | 4 u 8 |
| Tipo Numérico | Complejo | Números complejos. | ```4+3i, 8i``` | 12 o 16 |
| Tipo Texto | Carácter | Representan un único símbolo o letra. | ```'a', 'B', '$'``` | 1 a 4 |
| Tipo Texto | Cadena de Texto | Secuencias de caracteres. | ```"Hola mundo", "Python es genial", "42"``` | Suma total de caracteres |
| Tipo booleano | Booleano | Valores de verdad o falso. | ```True, False``` | 1 |

Aquí pueden informarse más acerca de los [números de punto flotante.](http://puntoflotante.org/formats/fp/)

2. Tipos de datos estructurados (los veremos más adelante).

In [4]:
dato_entero = 37
tipo_de_dato = type(dato_entero)
print(type(dato_entero))

<class 'int'>


In [5]:
dato_decimal = 37.24
tipo_de_dato = type(dato_decimal)
print(type(dato_decimal))

<class 'float'>


In [6]:
dato_caracter = '%'
tipo_de_dato = type(dato_caracter)
print(type(dato_caracter))

<class 'str'>


In [7]:
dato_cadena_de_caracteres = "Soy una cadena de caracteres"
tipo_de_dato = type(dato_cadena_de_caracteres)
print(type(dato_cadena_de_caracteres))

<class 'str'>


In [8]:
dato_booleano = True
tipo_de_dato = type(dato_booleano)
print(type(dato_booleano))

<class 'bool'>


### Variables: declaración, asignación e inicialización

Una *variable* es como un contenedor de datos que tiene un _nombre_ y un _valor_. El nombre de la variable se utiliza para referirse al valor almacenado en el contenedor. El valor de la variable puede cambiar durante la ejecución del programa.

Las variables se utilizan para almacenar y manipular datos de diferentes tipos, ya sean primitivos o estructurados. Son esenciales para escribir código organizado y reutilizable, ya que permiten evitar la repetición de código y hacen que el programa sea más fácil de leer y entender.

Características principales de las variables:

- _Nombre_: Un identificador único que se utiliza para referirse a la variable.

- _Tipo de dato_: El tipo de dato que la variable puede almacenar.

- _Valor_: El dato actual almacenado en la variable.

- _Alcance_: La parte del programa donde la variable es visible y accesible.


Declaración de una variable:

La declaración de una variable consiste en definir un nombre para la variable y especificar el tipo de dato que puede almacenar. Esto se hace utilizando una instrucción de declaración de variables, la cual varía según el lenguaje de programación que se esté utilizando.

In [7]:
# Declaración de una variable entera
mi_variable_entera: int

# Declaración de una variable decimal
mi_variable_decimal: float

# Declaración de una variable de una cadena de caracteres
mi_variable_cadena_char: str

# Declaración de una variable booleana
mi_variable_booleana: bool

Asignación de una variable:

La asignación de una variable consiste en atribuir un valor a la variable previamente declarada. Esto se hace utilizando el operador de asignación ```=``` seguido del valor que se quiere asignar, es decir, ```variable = valor```, que es equivalente a hacer lo siguiente: ```variable <- valor```.

In [8]:
# Asignación de un valor a la variable entera
mi_variable_entera = 10

# Asignación de un valor a la variable decimal
mi_variable_decimal = 3.1416

# Asignación de un valor a la variable de cadena de caracteres
mi_variable_cadena_char = "Hola chicos de ambientales"

# Asignación de un valor a la variable booleana
mi_variable_booleana = True

Inicialización de una variable:

La inicialización de una variable es el proceso de asignar un valor a la variable al mismo tiempo que se declara. Esto se puede hacer en la misma instrucción de declaración de la variable.

Alcance de una variable:

In [9]:
variable_1 = "Variable 1: tengo alcance global."

print(variable_1)

Variable 1: tengo alcance global.


In [16]:
def fun_1():
    print("Estamos dentro de la función fun_1:")
    print("\t" + variable_1)

fun_1()

Estamos dentro de la función fun_1:
	Variable 1: tengo alcance global.


In [10]:
def fun_2():
    print("Estamos dentro de la función fun_2:")
    variable_2 = "Variable 2: tengo alcance solo dentro de la función fun_2:"
    print("\t" + variable_2)

In [11]:
try:
    print(variable_2)
except:
    print("variable_2 no está al alcance, posiblemente no definida.")

fun_2()

variable_2 no está al alcance, posiblemente no definida.
Estamos dentro de la función fun_2:
	Variable 2: tengo alcance solo dentro de la función fun_2:


In [13]:
def fun_3():
    print("Estamos dentro de la función fun_3:")

    variable_3 = "Variable 3: tengo alcance solo dentro de la función fun_3"

    print("\t" + variable_3)
    print("\t" + variable_1 + " También dentro de la función fun_3.")

    try:
        print(variable_4)
    except:
        print("variable_4 no está al alcance, posiblemente no definida.")

    def fun_4():
        print("\tEstamos dentro de la función fun_4:")
        
        variable_4 = "Variable 4: tengo alcance solo dentro de la función fun_4."
        
        print("\t\t" + variable_4)
        print("\t\t" + variable_3 + " y también dentro de la función fun_4.")
        print("\t\t" + variable_1 + " y también dentro de la función fun_4.")
        
    
    fun_4()

In [14]:
fun_3()

Estamos dentro de la función fun_3:
	Variable 3: tengo alcance solo dentro de la función fun_3
	Variable 1: tengo alcance global. También dentro de la función fun_3.
variable_4 no está al alcance, posiblemente no definida.
	Estamos dentro de la función fun_4:
		Variable 4: tengo alcance solo dentro de la función fun_4.
		Variable 3: tengo alcance solo dentro de la función fun_3 y también dentro de la función fun_4.
		Variable 1: tengo alcance global. y también dentro de la función fun_4.


#### Convención para nombrar variables, funciones y archivos en python

El **snake case**, también conocido como **lowercase_with_underscores**, es una convención de nomenclatura utilizada en programación para nombrar variables, funciones y archivos. Consiste en escribir las palabras en minúsculas separadas por guiones bajos **(_)**.

Características principales del snake case:

- *Mejora la legibilidad:* Al separar las palabras con guiones bajos, los nombres de variables largos son más fáciles de leer y comprender.

- *Consistencia:* Usar snake case de manera consistente en todo tu código mejora la mantenibilidad del código y facilita que otros programadores lo entiendan.

- *Convención común:* Snake case es una convención ampliamente utilizada en Python y muchos otros lenguajes de programación.

Ejemplos de snake case, para nombres de variables:

```python
    resultado_aproximado
    ventas_totales
    calcular_promedio
```
y para nombre de archivos:
```
mi_primer_programa_en_python.py
```

Las constantes en python (también en otros lenguajes de programación) se escriben en mayúsculas usando la convención **snake_case**. Por ejemplo:
```python
    PI = 3.1416
    GRAVEDAD = 9.81
```

## 2. Operadores

### Operadores aritméticos y orden de precedencia

Los operadores aritméticos se utilizan para realizar operaciones matemáticas básicas con números. En lenguajes de programación, el orden en que se evalúan estas operaciones está definido por la precedencia de los operadores. La precedencia dictamina qué operaciones se realizan primero y en qué orden.

<div style="display: flex; justify-content: center;">

| Precendencia | Operador | Descripción | Asociatividad |
| :---: | :---: | :---: | :---: |
| 1 | **(expresion)** | Expresión entre paréntesis | Izquierda a derecha |
| 2 | **\*\*** | Exponente | Izquierda a derecha |
| 3 | **\*, /, //, %** | Multiplicación, división, cociente y módulo | Izquierda a derecha |
| 4 | **+, -** | Suma y resta | Izquierda a derecha |

</div>

In [15]:
4 + 6 * 3**2 - 34 / 8 - 12 % 7

48.75

##### Exponente

In [12]:
# Exponente con operador **
numero = 56
exponente = 2
numero_elevado_a_exponente = numero**exponente          # 56 ** 2
print(f"{numero}^2 = {numero_elevado_a_exponente}")

56^2 = 3136


In [13]:
# Exponente con la función pow
import math

numero = 56
exponente = 2
numero_elevado_al_cuadrado = math.pow(numero, exponente)    # math.pow(56, 2)
print(f"{numero}^2 = {numero_elevado_al_cuadrado}")

56^2 = 3136.0


##### Operador division, Cociente y Módulo

Recordemos la expresión de la división exacta:

$dividendo = cociente \times divisor$

In [14]:
# Operador división /: cociente real, considera el residuo

dividendo = 57
divisor = 2
cociente = dividendo / divisor
print(f"{dividendo} / {divisor} = {cociente}")

57 / 2 = 28.5


In [15]:
print(f"La fórmula de la división:")
print(f"{dividendo} = {cociente} x {divisor}")

La fórmula de la división:
57 = 28.5 x 2


##### División Entera

Recordemos la expresión de la división entera:

$dividendo = cociente \times divisor + residuo$

In [16]:
# Operador división entera //: obtenemos el cociente entero, no considera el residuo

dividendo = 57
divisor = 2
cociente_entero = dividendo // divisor
print(f"{dividendo} // {divisor} = {cociente_entero}")

57 // 2 = 28


In [17]:
# Operador módulo %: obtiene residuo

dividendo = 57
divisor = 2
residuo = dividendo % divisor
print(f"{dividendo} % {divisor} = {residuo}")

57 % 2 = 1


In [18]:
print(f"La expresión de la divisón entera:")
print(f"{dividendo} = {cociente} x {divisor} + {residuo}")

La expresión de la divisón entera:
57 = 28.5 x 2 + 1


### Operadores de Asignación

Los operadores de asignación se utilizan para asignar valores a variables. El operador de asignación más común es ```=```.

Otros operadores de asignación:

<div style="display: flex; justify-content: center;">

| Operador | Descripción |
| :---: | :---: |
| += | Suma y asigna |
| -= | Resta y asigna |
| *= | Multiplica y asigna |
| /= | Divide y asigna|
| %= | Módulo y asigna |
</div>

In [19]:
numero = 45
numero += 5
print(f"El valor de numero = {numero}")

El valor de numero = 50


In [20]:
numero = 45
numero -= 5
print(f"El valor de numero = {numero}")

El valor de numero = 40


In [21]:
numero = 45
numero *= 5
print(f"El valor de numero = {numero}")

El valor de numero = 225


In [22]:
numero = 45
numero /= 5
print(f"El valor de numero = {numero}")

El valor de numero = 9.0


In [23]:
numero = 45
numero %= 5
print(f"El valor de numero = {numero}")

El valor de numero = 0


### Operadores de Relación e Igualdad

Los operadores de relación e igualdad se utilizan para comparar valores.

Operadores de relación:

<div style="display: flex; justify-content: center;">

| Operador | Descripción |
| :---: | :---: |
| < | Menor que |
| <= | Menor o igual que |
| > | Mayor que |
| >= | Mayor o igual que |
| == | Igual que |
| != | Distinto que |
</div>

In [24]:
numero_1 = 45
numero_2 = 56

numero_1 < numero_2

True

In [25]:
numero_1 = 45
numero_2 = 56

numero_1 <= numero_2

True

In [26]:
numero_1 = 45
numero_2 = 56

numero_1 > numero_2

False

In [27]:
numero_1 = 45
numero_2 = 56

numero_1 >= numero_2

False

In [28]:
numero_1 = 45
numero_2 = 56

numero_1 == numero_2

False

In [29]:
numero_1 = 45
numero_2 = 56

numero_1 != numero_2

True

### Operadores Lógicos

Los operadores lógicos se utilizan para combinar dos o más expresiones booleanas en una sola expresión booleana.

Operadores lógicos:

<div style="display: flex; justify-content: center;">

| Operador | Operador en Python | Descripción |
| :---: | :---: | :---: |
| and | && | Y (ambas expresiones deben ser verdaderas) |
| or | \|\| | O (al menos una expresión debe ser verdadera) |
| not | ~ | No (invierte el valor de la expresión) |
</div>

In [30]:
numero_1 = 45
numero_2 = 87

numero_1 < numero_2 and numero_2 == 81

False

In [31]:
numero_1 = 45
numero_2 = 87

numero_1 > numero_2 or numero_2 == 87

True

In [32]:
numero_1 = 45
numero_2 = 87

not(numero_1 > numero_2)

True

## 3. Estructuras de Control

Las estructuras de control son bloques de código que permiten controlar el flujo de ejecución de un programa.

Las estructuras de control son esenciales para la programación, ya que permiten:

- **Modularizar el código:** Dividir el programa en bloques más pequeños y manejables, mejorando la legibilidad y el mantenimiento del código.
- **Tomar decisiones:** Permitir al programa responder a diferentes condiciones y situaciones.
- **Repetir tareas:** Automatizar la ejecución de tareas repetitivas, ahorrando tiempo y esfuerzo.
- **Crear algoritmos complejos:** Combinando diferentes estructuras de control, se pueden crear algoritmos sofisticados para resolver problemas complejos.

### Estructuras secuenciales:

Las estructuras secuenciales, también conocidas como instrucciones lineales, ejecutan las instrucciones una tras otra en un orden descendente. Es la forma más básica de controlar el flujo del programa. La sintaxis básica es la siguiente:

```algorithm
    begin
        <Instrucción_1>
        <Instrucción_2>
        <Instrucción_3>
              .
              .
              .
        <Instrucción_n>
    end
```

En en lenguaje de programación FORTRAN se usa la siguiente sintaxis:
```fortran
    PROGRAM <nombre_del_programa>
        <Instrucción_1>
        <Instrucción_2>
        <Instrucción_3>
              .
              .
              .
        <Instrucción_n>
    END PROGRAM
```
Python no usa sentencias especiales para delimitar sus estructuras secuenciales.

In [33]:
# Ejemplo en python:

PI = 3.1416     #! Constantes en mayúsculas
radio = 6.4
radio_cuadrado = radio**2
area_circulo = PI * radio_cuadrado
print(f"El área del círculo de radio = {radio} es igual a {area_circulo}")

El área del círculo de radio = 6.4 es igual a 128.67993600000003


### Estructuras selectivas

Las estructuras **selectivas**, también conocidas como **condicionales**, permiten al programa tomar decisiones en función de una o más condiciones. Permiten ejecutar diferentes bloques de código según el resultado de la evaluación de la condición.

Las estructuras selectivas más comunes son:

- Instrucción **if**: Evalúa una condición y ejecuta un bloque de código si la condición es verdadera. La sintaxis es la siguiente:
```algoritmos
    if <condición> then
        <bloque_de_código>
    endIf
```

La estructura ```if``` en el lenguaje de programación C se escribe como:
```c
    if (<condición>)
    {
        <bloque_de_código>
    }
```
La sintaxis en python es:

```python
    if <condición>:
        <bloque_de_código>
```

In [34]:
comando = "salir"
CODIGO_DE_SALIDA = "salir"

if comando == CODIGO_DE_SALIDA:
    print("Hasta luego.")

print("Se ejecutan otras instrucciones...")

Hasta luego.
Se ejecutan otras instrucciones...


- Instrucción **if - else**: Evalúa una condición y ejecuta un bloque de código si la condición es verdadera, y otro bloque de código si la condición es falsa. Su sintaxis general es la siguiente:

```algorithm
    if <condición> then
        <bloque de código 1>
    else
        <bloque de código 2>
    endIf
```
FORTRAN utiliza esta sintaxis:
```fortran
    IF (<condición>) THEN
        <bloque_de_código>
    ELSE
        <bloque_de_código>
    END IF
```
La sintaxis para python es:
```python
    if <condición>:
        <bloque de código 1>
    else:
        <bloque de código 2>
```

In [35]:
edad = 13
EDAD_PARA_VOTAR = 18

if edad >= EDAD_PARA_VOTAR:
    print("Ya puedes tramitar tu INE.")
else:
    print("Aún no eres mayor de edad.")

print("Se ejecutan otras instrucciones...")

Aún no eres mayor de edad.
Se ejecutan otras instrucciones...


- Instrucción **if - elif - else**: Evalúa una o más condiciones y ejecuta el bloque de código correspondiente si la condición es verdadera, o evalúa el bloque de código **else** si ninguna de las condiciones anteriores se cumplió. La sintaxis general es la siguiente:

```algorithm
    if <condición> then
        <bloque de código 1>
    else if <condición> then
        <bloque de código 2>
    else if <condición> then
        <bloque de código 3>
                .
                .
                .
    else
        <bloque de código n>
    endIf
```

El lenguaje C adopta la siguiente sintaxis:
```c
    if (<condición>)
    {
        <bloque_de_código>
    } else if (<condición>)
    {
        <bloque_de_código>
    } else if (<condición>)
               .
               .
               .
    else 
    {
        <bloque_de_código>
    }
```

La sintaxis que utiliza python es:

```python
    if condicion:
        <bloque de código 1>
    elif:
        <bloque de código 2>
    elif:
        <bloque de código 3>
                .
                .
                .
    else:
        <bloque de código n>
```

In [36]:
edad = 66
costo_boleto = 0

if edad < 14:
    costo_boleto = 5
elif edad < 18:
    costo_boleto = 10
elif edad < 65:
    costo_boleto = 20
else:
    costo_boleto = 15

print(f"Tu costo de admisión es de ${costo_boleto} pesos.")

Tu costo de admisión es de $15 pesos.


### Estructuras Iterativas en Python

Las estructuras iterativas, también conocidas como **bucles** o **ciclos**, son bloques de código que permiten repetir un conjunto de instrucciones un número determinado de veces o hasta que se cumpla una condición. Son herramientas fundamentales para automatizar tareas repetitivas y crear algoritmos complejos.

Tipos de estructuras iterativas:

- Bucle **while**:

El bucle while se utiliza para repetir un bloque de código mientras se cumpla una condición. La sintaxis básica del bucle while es la siguiente:

```algoritmos
    while <condición> do
        <bloque de código>
    endWhile
```
La sintaxis del ciclo **while** en Python es:
```python
    while <condición>:
        <bloque de código>


In [37]:
i = 1

while i < 10:
    print(i)
    i += 1      #! La condición de salida es importante

1
2
3
4
5
6
7
8
9


Todo bucle while necesita una forma de dejar de ejecutarse para que no siga ejecutándose eternamente. Todo programador escribe accidentalmente un bucle while infinito de vez en cuando, especialmente cuando los bucles de un programa tienen sutiles condiciones de salida. Si su programa se queda atascado en un bucle infinito, pulse ```CTRL-C``` o simplemente cierre la ventana del terminal que muestra la salida de su programa. 

Para evitar escribir bucles infinitos, prueba cada bucle while y asegúrate de que el bucle se detiene cuando esperas que lo haga. Si el programa no termina, escudriñe la forma en que su programa maneja el valor que debería causar la salida del bucle. Asegúrese de que al menos una parte del programa puede hacer que la condición del bucle sea ```False```.

In [38]:
console = "\nDime algo, te lo voy a repetir:"
console += "\nEscribe 'exit' para salir de la aplicación. "
message = ""
while message != 'exit':
    message = input(console)
    print(message)


Dime algo, te lo voy a repetir:
Escribe 'exit' para salir de la aplicación.  Hola


Hola



Dime algo, te lo voy a repetir:
Escribe 'exit' para salir de la aplicación.  exit


exit


#### Sentencia ```break```

Para salir de un bucle while inmediatamente sin ejecutar ningún código restante en el bucle, independientemente de los resultados de cualquier prueba condicional, utilice la sentencia ```break```. La sentencia ```break``` dirige el flujo de tu programa dentro del bucle; puedes usarla para controlar qué líneas de código se ejecutan y cuáles no, de forma que el programa sólo ejecute el código que tú quieras, cuando tú quieras.

In [39]:
i = 1

while i < 10:

    if i % 4 == 0:
        break

    print(i)
    i += 1 

1
2
3


In [40]:
console = "\nEjemplo de uso de la sentencia break."
console += "\nEnter a integer number. "

while True:
    number = int(input(console))
    print(number)
    if number == 10:
        break


Ejemplo de uso de la sentencia break.
Enter a integer number.  10


10


In [41]:
console = "\nPlease enter the name of a city you have visited:"
console += "\n(Enter 'exit' when you are finished.) "

while True:
    city = input(console)
    if city == 'exit':
        break
    else:
        print(f"I'd love to go to {city.title()}!")


Please enter the name of a city you have visited:
(Enter 'exit' when you are finished.)  exit


#### Sentencia ```continue```

En lugar de salir completamente de un bucle sin ejecutar el resto de su código, puede utilizar la sentencia ```continue``` para volver al principio del bucle, basándose en el resultado de una prueba condicional.

In [42]:
i = 0

while i < 10:

    i += 1 

    if i % 4 == 0:
        continue

    print(i)


1
2
3
5
6
7
9
10


- Bucle **for**:

El bucle ```for``` se utiliza para repetir un bloque de código un número determinado de veces, especificado por una secuencia o un rango. La sintaxis básica del bucle ```for``` es la siguiente:

```algorithm
    for <variable> <- <valor inicial> to <valor final>
        <bloque de código>
    endFor
```

Ejemplo de bucle ```for``` en el lenguaje java:
```java
    for (i = 1; i < 10; i += 1) {
        <bloque de código que hace algo>
    }
```

La sintaxis del bucle ```for``` en python es:
```python
    for <variable de iteración> in <secuencia de valores a iterar>:
        <bloque de código>
```

In [43]:
for i in [1, 2, 3, 4, 5]:
    print(i)

1
2
3
4
5


#### Función ```range```

La función ```range()``` en Python es una herramienta fundamental para generar secuencias de números enteros de manera eficiente. Se utiliza principalmente en conjunto con bucles ```for``` para iterar sobre una secuencia de números.

La sintaxis básica de la función ```range()``` es la siguiente:

```python
    range(<inicio>, <fin>, <incremento>)
```

donde:

- inicio (opcional): Especifica el valor inicial de la secuencia. Por defecto, es 0.
- fin (opcional): Especifica el valor final de la secuencia. No se incluye en la secuencia. Por defecto, es el valor del inicio más el incremento.
- incremento (opcional): Especifica la diferencia entre los números consecutivos de la secuencia. Por defecto, es 1.

In [44]:
for i in range(1, 10, 2):
    print(i)

1
3
5
7
9


In [45]:
for string in ["hola", "chicos", "de", "ambientales"]:
    print(string)
    print(string.title())
    print(string.lower())
    print(string.upper())

hola
Hola
hola
HOLA
chicos
Chicos
chicos
CHICOS
de
De
de
DE
ambientales
Ambientales
ambientales
AMBIENTALES


## 3. Funciones

### Definición y llamada de funciones

Las funciones son bloques de código con nombre **definidos** para realizar un trabajo específico. Cuando quieras realizar una tarea concreta que hayas definido en una función, *llama* a la función responsable de ella. Si necesitas realizar esa tarea varias veces a lo largo de tu programa, no necesitas escribir todo el código para la misma tarea una y otra vez; simplemente llamas a la función dedicada a manejar esa tarea, y la *llamada* le dice a Python que ejecute el código dentro de la función. El uso de funciones hace que tus programas sean más **fáciles de escribir, leer, probar y corregir**.

La sintaxis general de una función es la siguiente:

```algorithm
    Function <tipo_de_dato_de_retorno> <- <nombre_de_la_función>(<lista_de_parámetros>)

        <bloque_de_código>
    
    endFunction

```

En python la sintaxis para definir una función es:
```python
    def <nombre_de_la_función> (<Lista_de_parámetros>):
        <bloque_de_código>
```

Así se define una función en el lenguaje de Rust:
```rust
    fn <nombre_de_la_función>(<Lista_de_parámetros>) -> <tipo_de_dato_de_retorno> {
        <bloque_de_código>
    }
```
Para el lenguaje de programación C se usa la siguiente sintaxis:
```c
    <tipo_de_dato_de_retorno> <nombre_de_la_función>(<lista_de_parámetros>) 
    {
        <bloque_de_código>
    }
```

In [46]:
# Ejemplo de definición de funciones
import math

def funcion_para_saludar():
    print("Hola chicos de ambientales, soy una función")

def funcion_para_saludar_con_argumentos(pon_tu_nombre_aqui):
    print(f"Muchos gusto {pon_tu_nombre_aqui}, te saluda una función")

def calcular_terna_pitagorica(numero_natural_1, numero_natural_2):
    valor_a = math.pow(numero_natural_1, 2) - math.pow(numero_natural_2, 2)
    valor_b = 2.0 * numero_natural_1 * numero_natural_2
    valor_c = math.pow(numero_natural_1, 2) + math.pow(numero_natural_2, 2)
    print(f"La terna pitagórica formada por los números naturales {numero_natural_1} y {numero_natural_2} es")
    print(f"({valor_a}, {valor_b}, {valor_c})")

In [47]:
funcion_para_saludar()
funcion_para_saludar_con_argumentos("Edwin")
calcular_terna_pitagorica(5, 3)

Hola chicos de ambientales, soy una función
Muchos gusto Edwin, te saluda una función
La terna pitagórica formada por los números naturales 5 y 3 es
(16.0, 30.0, 34.0)


### Parámetros y argumentos

En programación, los **parámetros** y los **argumentos** son conceptos fundamentales para entender el funcionamiento de las funciones. Si bien están estrechamente relacionados, tienen roles y características distintivas.

Parámetros: Los parámetros son las variables que se definen en la declaración de una función. Son como espacios reservados que esperan recibir valores cuando la función sea llamada. Se encuentran dentro de los paréntesis cuando se define la función.

Argumentos: Los argumentos son los valores que se pasan a una función cuando esta es llamada. Son los valores que se "llenan" en los espacios reservados de los parámetros. Se encuentran en los paréntesis cuando se llama a la función.

### Paso de argumentos.

Existen dos formas principales de pasar argumentos a una función:

- **Paso por valor**: En este caso, se copia el valor del argumento a la variable del parámetro dentro de la función. Cualquier modificación que se haga a la variable del parámetro dentro de la función no afecta al valor original del argumento.

- **Paso por referencia**: En este caso, se pasa la referencia (dirección de memoria) de la variable del argumento a la variable del parámetro dentro de la función. Cualquier modificación que se haga a la variable del parámetro dentro de la función también modifica el valor original del argumento.

In [35]:
variable = 5
def modificar_valor(variable):
    variable *= 2
# ---------------------------------
print(variable)
modificar_valor(variable)
print(variable)

5
5


In [37]:
list = [1, 2, 3]
def modificar_valor(list):
    for i in range(3):
        list[i] *= 2
# ---------------------------------
print(list)
modificar_valor(list)
print(list)

[1, 2, 3]
[2, 4, 6]


In [19]:
# list = [1, 2, 3]
# for i in range(len(list)):
#     print(list[i])

# for i,n in enumerate(list):
#     print(f"i = {i} y n = {n}.")

### Recuperación de valores

Una función no siempre tiene que mostrar su salida directamente. En su lugar, puede procesar algunos datos y luego devolver un valor o conjunto de valores. El valor que devuelve la función se denomina **valor de retorno**. La sentencia ```return``` toma un valor del interior de una función y lo devuelve a la línea que llamó a la función. Los valores de retorno le permiten mover gran parte del trabajo pesado de su programa a las funciones, lo que puede simplificar el cuerpo de su programa.

Cuando se llama a una función que devuelve un valor, es necesario proporcionar una variable a la que se pueda asignar el valor devuelto.

In [48]:
def obtener_saludo():
    saludo = "Hola chicos de ambientales, soy una función"
    return saludo

def obtener_saludo_para(nombre):
    saludo = f"Muchos gusto {nombre}, te saluda una función"
    return saludo

def obtener_terna_pitagorica(numero_natural_1, numero_natural_2):
    valor_a = math.pow(numero_natural_1, 2) - math.pow(numero_natural_2, 2)
    valor_b = 2.0 * numero_natural_1 * numero_natural_2
    valor_c = math.pow(numero_natural_1, 2) + math.pow(numero_natural_2, 2)
    return valor_a, valor_b, valor_c

In [49]:
saludo_obtenido = obtener_saludo()
print(saludo_obtenido)

Hola chicos de ambientales, soy una función


In [50]:
saludo_especial = obtener_saludo_para("Andrea")
print(saludo_especial)

Muchos gusto Andrea, te saluda una función


In [51]:
numero_natural_1 = 5
numero_natural_2 = 3
valor_1, valor_2, valor_3 = obtener_terna_pitagorica(numero_natural_1, numero_natural_2)

print(f"La terna pitagórica formada por los números naturales {numero_natural_1} y {numero_natural_2} es")
print(f"({valor_1}, {valor_2}, {valor_3})")

La terna pitagórica formada por los números naturales 5 y 3 es
(16.0, 30.0, 34.0)


## Estructura de datos

Las estructuras de datos son la base fundamental para organizar y almacenar información en un programa. La elección de la estructura de datos adecuada es crucial para el rendimiento y la eficiencia de un programa. 

Existen dos tipos principales de estructuras de datos:

1. Estructuras de datos lineales:

    - Arreglos (Arrays): Un arreglo es una colección de elementos del mismo tipo almacenados en posiciones contiguas de memoria. Se accede a cada elemento mediante un índice numérico. Los arreglos son estructuras de datos estáticas, lo que significa que su tamaño se define en tiempo de compilación y no se puede modificar durante la ejecución del programa.

    - Listas enlazadas: Una lista enlazada es una colección de elementos, llamados nodos, conectados entre sí por punteros. Cada nodo contiene un valor y un puntero al siguiente nodo en la lista. Las listas enlazadas son estructuras de datos dinámicas, lo que significa que su tamaño puede cambiar durante la ejecución del programa.

    - Pilas (Stacks): Una pila es una estructura de datos LIFO (Last In, First Out). Esto significa que el último elemento agregado a la pila es el primero en ser eliminado. Las pilas se utilizan comúnmente para implementar algoritmos de retroceso y deshacer.

    - Colas (Queues): Una cola es una estructura de datos FIFO (First In, First Out). Esto significa que el primer elemento agregado a la cola es el primero en ser eliminado. Las colas se utilizan comúnmente para implementar sistemas de búfer y tareas de procesamiento por orden de llegada.

2. Estructuras de datos no lineales:

    - Árboles: Un árbol es una estructura de datos jerárquica que consiste en un nodo raíz, conectado a cero o más nodos secundarios. Cada nodo puede tener cero o más hijos. Los árboles se utilizan comúnmente para representar datos jerárquicos, como sistemas de archivos y árboles de expresión.

    - Grafos: Un grafo es una estructura de datos que consiste en un conjunto de nodos (vértices) y un conjunto de aristas que conectan pares de nodos. Los grafos se utilizan comúnmente para representar relaciones entre entidades, como redes sociales y mapas de carreteras.

    - Tablas hash: Una tabla hash es una estructura de datos que asocia claves con valores. La clave se utiliza para calcular un índice en la tabla, donde se almacena el valor correspondiente. Las tablas hash son muy eficientes para buscar y almacenar datos.

## 

## Arreglos en python e introducción a NumPy.

### NumPy: La base para el cómputo científico en Python

NumPy, abreviatura de Numerical Python, es la biblioteca principal de Python para realizar cálculos numéricos. Permite la creación de arreglos y matrices multidimensionales de gran tamaño y proporciona una amplia colección de funciones matemáticas de alto nivel para operar con estos arreglos.

Las operaciones en NumPy son más rápidas y eficientes que la funcionalidad equivalente en la biblioteca estándar que se incluye con Python.

Para comprender los arreglos, es necesario conocer su estructura. El número de dimensiones en un arreglo es la cantidad de índices necesarios para seleccionar un elemento del mismo. Se puede pensar en una dimensión como un eje del arreglo.

El número de dimensiones en un arreglo, también llamado rango, se puede utilizar para describir el arreglo. En la figura se puede ver un ejemplo gráfico de arreglos unidimensionales, bidimensionales y tridimensionales.

<div style="text-align: center;">
    <img src="../images/numpy_arrays.png" alt="Banner curso" style="width:40%">
</div>

La forma de un arreglo es una tupla de enteros que representan el tamaño del arreglo a lo largo de cada dimensión, comenzando por la primera dimensión (eje 0). Se muestran ejemplos de formas debajo de cada arreglo en la figura anterior. El número de enteros en estas tuplas es igual al rango del arreglo.

<!-- <div style="text-align: center;">
    <img src="../images/NumPy-array.webp" alt="Banner curso" style="width:40%">
</div> -->

In [2]:
import numpy as np  # Importamos la librería

# Crear un arreglo unidimensional
arreglo_unidimensional = np.array([5, 4, 9])
print(arreglo_unidimensional)
print(f"Shape: {arreglo_unidimensional.shape}")

[5 4 9]
Shape: (3,)


In [6]:
# Crear un arreglo bidimensional
arreglo_tridimensional = np.array([
                                    [4.1, 2.0, 6.7],
                                    [0.3, 9.4, 2.2]
                                ])
print(arreglo_tridimensional)
print(f"Shape: {arreglo_tridimensional.shape}")

[[4.1 2.  6.7]
 [0.3 9.4 2.2]]
Shape: (2, 3)


In [11]:
# Crear un arreglo tridimensional
arreglo_tridimensional = np.array([[[1, 0, 1, 1],
                                   [0, 1, 1, 1],
                                   [1, 1, 0, 1]],

                                  [[0, 0, 0, 0],
                                   [0, 0, 0, 0],
                                   [1, 1, 0, 1]]])
print(arreglo_tridimensional)
print(f"Shape: {arreglo_tridimensional.shape}")

[[[1 0 1 1]
  [0 1 1 1]
  [1 1 0 1]]

 [[0 0 0 0]
  [0 0 0 0]
  [1 1 0 1]]]
Shape: (2, 3, 4)
Size: 24


### Atributos de los arreglos

#### Arreglos unidimensionales

In [21]:
vector = np.array([2,4,6,8,10])

# ndim: Devuelve el número de dimensiones del array.
numero_de_dimensiones_del_vector = vector.ndim
print(f'El número de dimensiones del vector es: {numero_de_dimensiones_del_vector}')

# shape: Devuelve una tupla con las dimensiones del array.
dimensiones_del_vector = vector.shape
print(f'El número de dimensiones del vector es: {dimensiones_del_vector}')

# size:  Devuelve el número de elementos del array.
numero_de_elementos_del_vector = vector.size
print(f'El número de elementos del vector es: {numero_de_elementos_del_vector}')

# dtype: Devuelve el tipo de datos de los elementos del array.
tipo_de_dato_del_vector = vector.dtype
print(f'El tipo de dato del vector es: {tipo_de_dato_del_vector}')

print(f'El vector es:')
print(vector)

El número de dimensiones del vector es: 1
El número de dimensiones del vector es: (5,)
El número de elementos del vector es: 5
El tipo de dato del vector es: int64
El vector es:
[ 2  4  6  8 10]


#### Arreglos bidimensionales

In [25]:
matriz = np.array([
        [2,4,6,8,10],
        [4,16,36,64,100],
        [2.3,4.3,6.3,8.3,10.3]
    ])

# ndim: Devuelve el número de dimensiones del array.
numero_de_dimensiones_de_la_matriz = matriz.ndim
print(f'El número de dimensiones de la matriz es: {numero_de_dimensiones_de_la_matriz}')

# shape: Devuelve una tupla con las dimensiones del array.
dimensiones_de_la_matriz = matriz.shape
print(f'El número de dimensiones de la matriz es: {dimensiones_de_la_matriz}')

# size:  Devuelve el número de elementos del array.
numero_de_elementos_de_la_matriz = matriz.size
print(f'El número de elementos de la matriz es: {numero_de_elementos_de_la_matriz}')

# dtype: Devuelve el tipo de datos de los elementos del array.
tipo_de_dato_de_la_matriz = matriz.dtype
print(f'El tipo de dato del matriz es: {tipo_de_dato_de_la_matriz}')

print(f'La matriz es:')
print(matriz)

El número de dimensiones de la matriz es: 2
El número de dimensiones de la matriz es: (3, 5)
El número de elementos de la matriz es: 15
El tipo de dato del matriz es: float64
La matriz es:
[[  2.    4.    6.    8.   10. ]
 [  4.   16.   36.   64.  100. ]
 [  2.3   4.3   6.3   8.3  10.3]]


#### Acceder a los valores de un arreglo

In [32]:
print(f'El vector es:')
print(vector)

# Para un arreglo unidimensional, se accede de la siguiente manera:
indice = 3
valor = vector[indice]
print(f'vector[{indice}] = {valor}')

El vector es:
[ 2  4  6  8 10]
vector[3] = 8


In [39]:
print(f'La matriz es:')
print(matriz)

# Primera forma
indice_fila = 2
indice_columna = 3
valor = matriz[indice_fila, indice_columna]
print(f'Primera forma: matriz[{indice_fila}, {indice_columna}] = {valor}')

# Segunda forma
valor = matriz[indice_fila][indice_columna]
print(f'Segunda forma: matriz[{indice_fila}][{indice_columna}] = {valor}')

La matriz es:
[[  2.    4.    6.    8.   10. ]
 [  4.   16.   36.   64.  100. ]
 [  2.3   4.3   6.3   8.3  10.3]]
Primera forma: matriz[2, 3] = 8.3
Segunda forma: matriz[2][3] = 8.3


### Obtener subarreglos

In [46]:
# Generar temperaturas de 10 elementos
temperaturas = np.random.uniform(1, 10, 10)

# Formatear a dos decimales
temperaturas = np.around(temperaturas, decimals=2)

print(temperaturas)

[7.6  2.55 1.09 3.34 1.87 6.96 5.31 3.7  2.02 1.74]


In [79]:
# En el caso de arreglos unidimensionales
vector = [1,2,3,4,5,6,7,8,9,10]

sub_vector = vector[4:10]
# sub_vector = vector[:]
print(f'sub_vector = {sub_vector}')

sub_vector = [5, 6, 7, 8, 9, 10]


In [29]:
# En el caso de arreglos bidimensionales
matriz = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]
])

print(matriz)
sub_matriz = matriz[3, :]
# sub_matriz = matriz[2, 0:3]
# sub_matriz = matriz[:, 3]
# sub_matriz = matriz[1:4, 3]
# sub_matriz = matriz[1:3, :]
# sub_matriz = matriz[:, 1:3]
# sub_matriz = matriz[1:3, 2:4]
# sub_matriz = matriz[:, :]
print(f'sub_matriz = {sub_matriz}')

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
sub_matriz = [16 17 18 19 20]


### Funciones para generar arreglos.

La función `np.arange` genera un array con valores dentro de un intervalo especificado, con un paso constante entre cada valor.
```python
    np.arrange(start, end, step)
```

In [45]:
start_a = 0
end_a = 10
step_a = 3

arrange_1 = np.arange(end_a) # step por default es uno y start por default es cero
print(arrange_1)

arrange_2 = np.arange(start_a, end_a)
print(arrange_2)

arrange_3 = np.arange(start_a, end_a + 1) # Si queremos se incluya el valor end_a, entonces end_a + 1
print(arrange_3)

arrange_4 = np.arange(start_a, end_a + 1, step_a) 
print(arrange_4)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10]
[0 3 6 9]


La función `np.linspace` genera un array con un número especificado de valores equidistantes dentro de un intervalo.
```python
    np.linspace(start, end, num)
```

In [72]:
start_l = 0
end_l = 2
num_l = 5

linspace_1 = np.linspace(start_l, end_l) # no hay valor start por default y num por default es 50
print(linspace_1)
print()

linspace_2 = np.linspace(start_l, end_l, num_l) 
print(linspace_2)
print()

linspace_3 = np.linspace(0,2,5, endpoint=False) # para no incluir valor end
print(linspace_3)

[0.         0.04081633 0.08163265 0.12244898 0.16326531 0.20408163
 0.24489796 0.28571429 0.32653061 0.36734694 0.40816327 0.44897959
 0.48979592 0.53061224 0.57142857 0.6122449  0.65306122 0.69387755
 0.73469388 0.7755102  0.81632653 0.85714286 0.89795918 0.93877551
 0.97959184 1.02040816 1.06122449 1.10204082 1.14285714 1.18367347
 1.2244898  1.26530612 1.30612245 1.34693878 1.3877551  1.42857143
 1.46938776 1.51020408 1.55102041 1.59183673 1.63265306 1.67346939
 1.71428571 1.75510204 1.79591837 1.83673469 1.87755102 1.91836735
 1.95918367 2.        ]

[0.  0.5 1.  1.5 2. ]

[0.  0.4 0.8 1.2 1.6]


La función `np.zeros` crea un array de ceros con la forma especificada.
```python
    np.zeros(shape)
```

In [53]:
shape_unidimensional = (4,)
shape_bidimensional = (3,4)

vector = np.zeros(shape_unidimensional)
matriz = np.zeros(shape_bidimensional)

print(vector)
print()
print(matriz)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


La función `np.ones` crea un array de unos con la forma especificada.
```python
    np.ones(shape)
```

In [54]:
shape_unidimensional = (4,)
shape_bidimensional = (3,4)

vector = np.ones(shape_unidimensional)
matriz = np.ones(shape_bidimensional)

print(vector)
print()
print(matriz)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


La función `np.full` crea un array lleno con un valor específico.
```python
    np.full(shape, fill_value)
```

In [71]:
shape_unidimensional = (4,)
shape_bidimensional = (3,4)

vector = np.full(shape_unidimensional, 4)
matriz = np.full(shape_bidimensional, 6.3)

print(vector)
print()
print(matriz)

[4 4 4 4]

[[6.3 6.3 6.3 6.3]
 [6.3 6.3 6.3 6.3]
 [6.3 6.3 6.3 6.3]]


La función `np.eye` permite crear una matriz con unos en la diagonal principal y ceros en otros lugares.
```python
    np.eye(N, M, k)
```

donde 
- N: Número de filas de la matriz.
- M: Número de columnas de la matriz. Si no se especifica, se toma como N.
- k: Índice de la diagonal. k=0 (por defecto) es la diagonal principal, k>0 es una diagonal por encima de la principal, y k<0 es una diagonal por debajo de la principal.

In [62]:
N = 4
M = 6
k = -1

matriz_1 = np.eye(N) # M es opcional y k es igual a uno por default
matriz_2 = np.eye(N,M)
matriz_3 = np.eye(N,M,k)
matriz_4 = np.eye(N,N,k)

print(matriz_1)
print()
print(matriz_2)
print()
print(matriz_3)
print()
print(matriz_4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]

[[0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


La función `np.identity` es una forma más simple de crear una matriz identidad (una matriz cuadrada con unos en la diagonal principal y ceros en otros lugares).
```python
    np.identity(n)
```
donde `n` es el número de filas (y columnas) de la matriz cuadrada.

In [67]:
N = 4

matriz = np.eye(N)

print(matriz)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Operaciones matemáticas con arrays

In [63]:
# Operación elemento a elemento:
vector_a = np.array([1,2,3,4,5])
vector_b = np.array([6,7,8,9,10])

print(f'vector_a + vector_b = {vector_a + vector_b}')
print(f'vector_a - vector_b = {vector_a - vector_b}')
print(f'vector_a * vector_b = {vector_a * vector_b}')
print(f'vector_b / vector_a = {vector_b / vector_a}')
print(f'vector_b % vector_a = {vector_b % vector_a}')
print(f'vector_a ** vector_b = {vector_a ** vector_b}')

vector_a + vector_b = [ 7  9 11 13 15]
vector_a - vector_b = [-5 -5 -5 -5 -5]
vector_a * vector_b = [ 6 14 24 36 50]
vector_b / vector_a = [6.         3.5        2.66666667 2.25       2.        ]
vector_b % vector_a = [0 1 2 1 0]
vector_a ** vector_b = [      1     128    6561  262144 9765625]


In [64]:
# Operación array-escalar:

print(f'vector_a + 5 = {vector_a + 5}')
print(f'vector_a - 5 = {vector_a - 5}')
print(f'vector_a * 5 = {vector_a * 5}')
print(f'vector_a / 5 = {vector_a / 5}')
print(f'vector_a % 5 = {vector_a % 5}')
print(f'vector_a ** 2 = {vector_a ** 2}')

vector_a + 5 = [ 6  7  8  9 10]
vector_a - 5 = [-4 -3 -2 -1  0]
vector_a * 5 = [ 5 10 15 20 25]
vector_a / 5 = [0.2 0.4 0.6 0.8 1. ]
vector_a % 5 = [1 2 3 4 0]
vector_a ** 2 = [ 1  4  9 16 25]


In [65]:
matriz_a = np.array([
    [1,2,3],
    [1,2,3],
    [1,2,3],
])

matriz_b = np.array([
    [5,6,7],
    [5,6,7],
    [5,6,7],
])

print(matriz_a)
print(matriz_b)
print(f'matriz_a + matriz_b = \n{matriz_a + matriz_b}')
print(f'matriz_a - matriz_b = \n{matriz_a - matriz_b}')
print(f'matriz_a * matriz_b = \n{matriz_a * matriz_b}')
print(f'matriz_b / matriz_a = \n{matriz_b / matriz_a}')
print(f'matriz_b % matriz_a = \n{matriz_b % matriz_a}')
print(f'matriz_a ** matriz_b = \n{matriz_a ** matriz_b}')

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[5 6 7]
 [5 6 7]
 [5 6 7]]
matriz_a + matriz_b = 
[[ 6  8 10]
 [ 6  8 10]
 [ 6  8 10]]
matriz_a - matriz_b = 
[[-4 -4 -4]
 [-4 -4 -4]
 [-4 -4 -4]]
matriz_a * matriz_b = 
[[ 5 12 21]
 [ 5 12 21]
 [ 5 12 21]]
matriz_b / matriz_a = 
[[5.         3.         2.33333333]
 [5.         3.         2.33333333]
 [5.         3.         2.33333333]]
matriz_b % matriz_a = 
[[0 0 1]
 [0 0 1]
 [0 0 1]]
matriz_a ** matriz_b = 
[[   1   64 2187]
 [   1   64 2187]
 [   1   64 2187]]


In [66]:
# Operación escalar-matriz
print(matriz_a)
print(f'matriz_a + 3 = \n{matriz_a + 3}')
print(f'matriz_a - 3 = \n{matriz_a - 3}')
print(f'matriz_a * 3 = \n{matriz_a * 3}')
print(f'matriz_a / 3 = \n{matriz_a / 3}')
print(f'matriz_a % 3 = \n{matriz_a % 3}')
print(f'matriz_a ** 2 = \n{matriz_a ** 2}')

[[1 2 3]
 [1 2 3]
 [1 2 3]]
matriz_a + 3 = 
[[4 5 6]
 [4 5 6]
 [4 5 6]]
matriz_a - 3 = 
[[-2 -1  0]
 [-2 -1  0]
 [-2 -1  0]]
matriz_a * 3 = 
[[3 6 9]
 [3 6 9]
 [3 6 9]]
matriz_a / 3 = 
[[0.33333333 0.66666667 1.        ]
 [0.33333333 0.66666667 1.        ]
 [0.33333333 0.66666667 1.        ]]
matriz_a % 3 = 
[[1 2 0]
 [1 2 0]
 [1 2 0]]
matriz_a ** 2 = 
[[1 4 9]
 [1 4 9]
 [1 4 9]]


### Función norm, dot, transpuesta (T), det, trace, inv y solve

In [6]:
vector = np.array([5, 6])
norma_vector = np.linalg.norm(vector)
print(f'La norma del vector norm(5i + 6j) = {norma_vector}')
print(f'La norma del vector norm(5i + 6j) = {np.around(norma_vector, decimals=2)}')

La norma del vector norm(5i + 6j) = 7.810249675906654
La norma del vector norm(5i + 6j) = 7.81


In [138]:
vector1 = np.ones(5,dtype=int)
vector2 = np.ones(5,int)*2
print(f'vector1 = {vector1}')
print(f'vector2 = {vector2}')

producto_punto = vector1.dot(vector2)
print(f'<vector1, vector2> = {producto_punto}')

vector1 = [1 1 1 1 1]
vector2 = [2 2 2 2 2]
<vector1, vector2> = 10


In [115]:
matriz1 = np.ones((4,4),int)
matriz2 = np.ones((4,4),int)*2

print(f'matriz1 = \n{matriz1}')
print(f'matriz2 = \n{matriz2}')

producto_matricial = np.dot(matriz1,matriz2)
print(f'matriz1 * matriz2 = \n{producto_matricial}')

matriz1 = 
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
matriz2 = 
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
matriz1 * matriz2 = 
[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [75]:
matriz = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

print(f'matriz = \n{matriz}')

matriz_transpuesta = matriz.T
print(f'matriz^T = \n{matriz_transpuesta}')



matriz = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
matriz^T = 
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [134]:
print(f'matriz = \n{matriz}')

traza_de_una_matriz = matriz.trace()

print(f'traza de matriz = {traza_de_una_matriz}')

matriz = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
traza de matriz = 34


In [135]:
print(f'matriz = \n{matriz}')

determinante = np.linalg.det(matriz)

print(f'determinante de matriz = {determinante}')

matriz = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
determinante de matriz = -1.820448242817726e-31


In [76]:
print(f'matriz = \n{matriz}')

inversa = np.linalg.inv(matriz)

print(f'inversa de la matriz = \n{inversa}')

matriz = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
inversa de la matriz = 
[[ 1.50119988e+15 -3.75299969e+14 -3.75299969e+15  2.62709978e+15]
 [-1.95155984e+16  1.95155984e+16  1.95155984e+16 -1.95155984e+16]
 [ 3.45275971e+16 -3.79052969e+16 -2.77721977e+16  3.11498974e+16]
 [-1.65131986e+16  1.87649984e+16  1.20095990e+16 -1.42613988e+16]]


In [137]:
vector_b = np.array([17, 18, 19, 20])

solucion = np.linalg.solve(matriz, vector_b)

print(f'La solucion del sistema es: {solucion}')


La solucion del sistema es: [ -0.41666667 -17.33333333  19.91666667  -1.91666667]
